# Generated by Django 2.2.5 on 2019-09-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno1', models.PositiveIntegerField(default=0)),
                ('regno2', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('postal', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('units', models.PositiveIntegerField(default=0)),
                ('busno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.BusinessInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cusno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.Customer')),
                ('prodno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.ProdInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('prodno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.ProdInfo')),
            ],
            options={
                'unique_together': {('prodno', 'start', 'end')},
            },
        ),
    ]
