# Generated by Django 2.2.5 on 2019-09-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0002_auto_20190927_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_ex1',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address_ex2',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
