# Generated by Django 2.2.5 on 2019-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0003_auto_20190927_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
