# Generated by Django 2.2.5 on 2019-09-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0004_auto_20190927_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='regno1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='regno2',
            field=models.CharField(max_length=5),
        ),
    ]
