# Generated by Django 2.2.5 on 2019-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0005_auto_20190927_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinfo',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
