# Generated by Django 2.2.5 on 2019-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0006_auto_20190927_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='regno3',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='regno2',
            field=models.CharField(max_length=2),
        ),
    ]
