# Generated by Django 2.2.5 on 2019-10-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMS', '0008_orderinfo_units'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('id', 'userid')},
        ),
    ]
